"usage: dmenu [-bfiv] [-l lines] [-p prompt] [-fn font] [-m monitor]       \n"
"             [-nb color] [-nf color] [-sb color] [-sf color] [-w windowid]\n"
"             [-bw border width]                      \n"
"             [-h line height]                        \n"
"             [-F (toggle fuzzy)]                     \n"
"             [-S (toggle numbers)]                   \n"
"             [-hi (toggle highlight)]                \n"
"             [-wd width] [-x x coord] [-y y coord]   \n"
"             [-it text]                              \n"
